name: seoulprism_map
description: "Testing 3D Map SDKs and Seoul Open Data integration for SeoulPrism project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Map Engine
  mapbox_maps_flutter: ^2.1.0
  
  # Utilities
  http: ^1.2.0
  cupertino_native_better: ^1.4.2
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/geojson/
