name: seoulprism_map
description: "Testing 3D Map SDKs and Seoul Open Data integration for SeoulPrism project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Map Engines (v2.x.x 이상으로 업데이트하여 Swift 호환성 해결)
  mapbox_maps_flutter: ^2.1.0
  google_maps_flutter: ^2.10.0
  flutter_naver_map: ^1.3.0
  
  # Utilities
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
